### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'avformat.so.58'

### ISSUE THREAD

**Issue by Slluxx** [exelix11/SysDVR#123]
**Setup information**
 - PC Os: ZorinOS (Ubuntu 64bit)
 - Console firmware: 11.0.1
 - Custom firmware name and version: Atmosphere 0.18.0
 - SysDVR version: latest

```
$ dotnet SysDVR-Client.dll bridge 192.168.2.152 --file test.mp4
SysDVR-Client - 5.1 by exelix
https://github.com/exelix11/SysDVR 

System.DllNotFoundException: Unable to load shared library 'avformat.so.58' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libavformat.so.58: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at FFmpeg.AutoGen.Native.NativeLibraryLoader.MapLinux(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at FFmpeg.AutoGen.ffmpeg.av_guess_format(String short_name, String filename, String mime_type)
   at SysDVR.Client.FileOutput.Mp4Output.Start()
   at SysDVR.Client.FileOutput.Mp4OutputManager.Begin()
   at SysDVR.Client.Program.StartStreaming(BaseStreamManager streams)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)
```

**Comment by exelix11** [comment]
`avformat.so.58` is missing, install ffmpeg or `libavformat-dev` from your package manager.
If that doesn't work you may need to make a synlink manually check the correct file name in /usr/lib/x86_64-linux-gnu/ and symlink it to avformat.so.58

**Comment by exelix11** [comment]
For reference: the same can happen with libusb and example commands are shown in [the guide](https://github.com/exelix11/SysDVR/wiki/USB-Driver#driver-setup-on-linux-and-mac)

**Comment by exelix11** [comment]
Uhm it means `av_guess_format` failed to find a proper mux for mp4 files which is pretty weird. It would mean your libavformat was compiled without mp4 support but it doesn't make much sense.
Could it be because you're using an old version ? You may have to compile libavcodec on your own or look for precompiled binary distributions from official sources.

**Comment by Slluxx** [comment]
honestly i dont know. and it seems too much hassle for me so ill just leave it be till i get a windows laptop again. but thanks for your time anyway!
