### ISSUE TITLE
[Bug] Does not work on Linux

### ISSUE THREAD

**Issue by Amenia1999** [exelix11/SysDVR#143]
Does not work on Linux.
 - PC Os:  Arch Linux
 - SysDVR-Client - 5.1
 - dotnet 5
 - sdl2

`dotnet SysDVR-Client.dll bridge 192.168.0.144
SysDVR-Client - 5.1 by exelix
https://github.com/exelix11/SysDVR 

System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)

`

**Comment by bleck9999** [comment]
Do you have the `extra/sdl2` package installed?

**Comment by Amenia1999** [comment]
yeah.

**Comment by Amenia1999** [comment]
It work with the dotnet installation script.

**Comment by writingeraser** [comment]
where to get this script?

**Comment by FieryMewtwo** [comment]
https://github.com/dotnet/install-scripts

**Comment by FieryMewtwo** [comment]
or just duckduckgo it ;)
