### ISSUE TITLE
[Help] Streaming via RTSP errors

### ISSUE THREAD

**Issue by GingerBobRoss** [exelix11/SysDVR#162]
I am having issues with Sys-DVR working via RTSP. USB cable works fine, but my switch is not able to play for long sessions as the battery drains faster than the device can charge connected to my PC.

When launching Sys-DVR using RTSP,  these errors listed below:

Starting stream, press return to stop.
Now streaming via RTSP on port 6666
Connect with your player to rtsp://127.0.0.1:6666/
Connection from 127.0.0.1:54654
RTSP message received Rtsp.Messages.RtspRequestOptions
RTSP message received Rtsp.Messages.RtspRequestDescribe
Request for rtsp://127.0.0.1:6666/
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestPlay
Terminating ReceiveFromDeviceThread for Audio due to System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
   at SysDVR.Client.Sources.TCPBridgeSource.WaitForConnection()
   at SysDVR.Client.StreamThread.DeviceThreadMain(CancellationToken token)
Terminating ReceiveFromDeviceThread for Video due to System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
   at SysDVR.Client.Sources.TCPBridgeSource.WaitForConnection()
   at SysDVR.Client.StreamThread.DeviceThreadMain(CancellationToken token)

 - PC OS: Windows 10 Pro x64
 - Console firmware: 13.0
 - CFW: Atmosphere 1.1.1
 - SysDVR 5.1 through MPV
 
 I have tried using the native playback, VLC, and MPV ( i dont know how to get MPV to work with RTSP) 
 IP address is correctly applied when using the ClientGUI.exe

**Comment by GingerBobRoss** [comment]
I fixed the issue, SYS-DVR setting shows to connect to USB "On-Boot" and was not correctly swapping over.
setting the simple connection back to "On-Bot" and selecting TCP-Bridge fixed the issue.
