### ISSUE TITLE
[Feature request] Ignore audio error: 'no endpoint found' when there are no audio output on system

### ISSUE THREAD

**Issue by ca1e** [exelix11/SysDVR#169]
**Is your feature request related to a problem? Please describe.**

Initializing video player with h264 codec.
System.Exception: Assertion failed: -1 WASAPI can't find requested audio endpoint: 

   at SysDVR.Client.Player.Exten.Assert(Int32 code, Func`1 MessageFun)
   at SysDVR.Client.Player.Player.InitSDLAudio(AudioStreamTarget target)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality, Boolean startFullScreen)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)

**Describe the solution you'd like**
when all audio devices disabled, "Both Channels" can simply ignore the audio chanel

**Comment by exelix11** [comment]
I considered implementing this but it's rather complicated as the current architecture separates data sources from players, this means that if the player decides to not play audio the source would still be reading packets from the console and processing them, it could be solved but it's just easier to use the video only option since it's already provided.
