### ISSUE TITLE
i cant Launch SysDVR-Client usb to begin streaming on macos

### ISSUE THREAD

**Issue by sticccck** [exelix11/SysDVR#186]
macos 10.15.7

 % SysDVR-Client usb                                                
zsh: command not found: SysDVR-Client

OR

 ~ % /Downloads/SysDVR-Client/SysDVR-Client.exe usb  
zsh: exec format error: /Downloads/SysDVR-Client/SysDVR-Client.exe

**Comment by kotleni** [comment]
### Use dotnet for launching this software.

**Comment by sticccck** [comment]
still problems

SysDVR-Client % dotnet SysDVR-Client.exe usb
Error:
  An assembly specified in the application dependencies manifest (SysDVR-Client.deps.json) has already been found but with a different file extension:
    package: 'SysDVR-Client', version: '5.3.0'
    path: 'SysDVR-Client.dll'
    previously found assembly: 'Downloads/SysDVR-Client/SysDVR-Client.exe'

**Comment by sticccck** [comment]
OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by sticccck** [comment]
I found this issues #https://github.com/exelix11/SysDVR/issues/179 
and try again.uninstall ffmpeg then install ffmpeg@4
libavcodec.58.dylib in my ffmpeg@4.I found
anything I am doing wrong ?

 ~ % dotnet /Users/Downloads/SysDVR-Client/SysDVR-Client.dll  usb
SysDVR-Client - 5.3 by exelix
https://github.com/exelix11/SysDVR 

System.DllNotFoundException: Unable to load shared library 'avcodec.58.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libavcodec.58.dylib, 1): image not found
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at FFmpeg.AutoGen.Native.NativeLibraryLoader.MapMac(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at FFmpeg.AutoGen.ffmpeg.avcodec_find_decoder(AVCodecID id)
   at SysDVR.Client.Player.Player.InitDecoder(Boolean hwAcc)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)
gaojingwen@gaojingwendeAir ~ % dotnet /Users/gaojingwen/Downloads/SysDVR-Client/SysDVR-Client.dll usb
SysDVR-Client - 5.3 by exelix
https://github.com/exelix11/SysDVR 

System.DllNotFoundException: Unable to load shared library 'avcodec.58.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libavcodec.58.dylib, 1): image not found
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at FFmpeg.AutoGen.Native.NativeLibraryLoader.MapMac(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at FFmpeg.AutoGen.ffmpeg.avcodec_find_decoder(AVCodecID id)
   at SysDVR.Client.Player.Player.InitDecoder(Boolean hwAcc)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)

**Comment by sticccck** [comment]
regretful

**Comment by sticccck** [comment]
This issue was settled.
Be all of /usr/local/Cellar/ffmpeg@4/4.4.2/lib copy in the SysDVR file directory
But found a new.
`$ dotnet SysDVR-Client.dll usb
SysDVR-Client - 5.3 by exelix
https://github.com/exelix11/SysDVR 

Initializing video player with h264 codec.
ERROR: SysDVR usb device not found.
Make sure that SysDVR is running in usb mode on your console and that you installed the correct driver.`

**Comment by pmakowski23** [comment]
Yeah same problem :c I was hoping this would work as I love this idea and I have lighter macbook that my windows laptop and I'd prefer taking it with me on trips.
