### ISSUE TITLE
[Bug] Apple Silicon search path wrong

### ISSUE THREAD

**Issue by AlanLi7991** [exelix11/SysDVR#192]
**Describe the bug**

On M1 chip, the default home-brew install path is not "/usr/local ", it is "/opt/homebrew"
That's why some people could not found dylib likes SDL2/libavcode/libavutil/libusb-1.0

Can refer the Homebrew official "https://docs.brew.sh/Installation"

```
This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon ...)
```

**To Reproduce**

Download the release version 5.3 and run it on M1

**Expected behavior**

Add default search path "/opt/homebrew" and use the replace name list

1.  "libavcodec.58.dylib" -> "libavcodec.dylib"
2.  "libavutil.56.dylib" -> "libavutil.dylib"

**Setup information**
 - PC Os:  MacBook Air M1
 - Console firmware 14.1.0
 - Custom firmware name and version AMS 1.3.2|E
 - SysDVR version 5.3

**Comment by exelix11** [comment]
Currently in master i do not manually search libraries anymore on non-windows and completely rely on dotnet's loader, can you check if the problem is solved using [Latest CI build](https://github.com/exelix11/SysDVR/actions/runs/2548326940) ?

> Is it possible not force to use the inner-control of Switch LITE, I used when I connect extra remote-control, the 5.3 version force change it to the LITE inner control

Not sure what you mean with this

**Comment by exelix11** [comment]
Did you also upgrade ffmpeg to 59 ? Before it used avcodec.58 but i had to upgrade

**Comment by AlanLi7991** [comment]
yes，avcodec I am using is 59，the latest version from homebrew

**Comment by exelix11** [comment]
I set `/opt/homebrew` as the default ffmpeg search path for mac os, can you try latest commit ?

**Comment by exelix11** [comment]
Had someone else test on m1 and the correct path seems to be `/opt/homebrew/lib`  but they had other problems locating SDL even though it should be installed. 
No clue what's going on with macos. I changed the path to `/opt/homebrew/lib` for arm macs which needs more testing and to `/usr/local/lib/` for intel macs which seems to be working fine

**Comment by AlanLi7991** [comment]
I test it on this release

https://github.com/exelix11/SysDVR/actions/runs/2649405908

same error as the latest stable version

```
z sh@zshs-M1 Client % dotnet SysDVR-Client.dll usb
SysDVR-Client - SysDVR 5.3 by exelix
https://github.com/exelix11/SysDVR 

There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --ffmpeg <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --ffmpeg $(brew --prefix)/lib/

Full error message:
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 0x0001): tried: 'libSDL2' (no such file), '/usr/local/lib/libSDL2' (no such file), '/usr/lib/libSDL2' (no such file), '/Users/zsh/Downloads/Client/libSDL2' (no such file)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
```

**Comment by exelix11** [comment]
This means it found ffmpeg but couldn't find sdl2, is that installed ? 
Can you check if it's correctly symlinked to /opt/homebrew/lib

In alternative you can try installing the dmg provided on the official site https://www.libsdl.org/download-2.0.php

**Comment by AlanLi7991** [comment]
you mean like this ?

```
zsh@zshs-M1 Client % export PATH=$PATH:/opt/homebrew/lib
zsh@zshs-M1 Client % dotnet SysDVR-Client.dll usb       
SysDVR-Client - SysDVR 5.3 by exelix
https://github.com/exelix11/SysDVR 

There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --ffmpeg <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --ffmpeg $(brew --prefix)/lib/

Full error message:
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 0x0001): tried: 'libSDL2' (no such file), '/usr/local/lib/libSDL2' (no such file), '/usr/lib/libSDL2' (no such file), '/Users/zsh/Downloads/Client/libSDL2' (no such file)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
zsh@zshs-M1 Client % 
```

**Comment by AlanLi7991** [comment]
Okay, here is my steps 
1. download the build https://github.com/exelix11/SysDVR/actions/runs/2649904594
2. uncompress the 7z package
3. cd to the directory 
4. execute "dotnet SysDVR-Client.dll usb"

the message is changed from SDL2 to lib-usb (which I am sure installed by homebrew)

```
zsh@zshs-M1 Client % dotnet SysDVR-Client.dll usb
SysDVR-Client - SysDVR 5.3 by exelix
https://github.com/exelix11/SysDVR 

Initializing video player with h264 codec.
There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --ffmpeg <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --ffmpeg $(brew --prefix)/lib/

Full error message:
System.DllNotFoundException: Unable to load shared library 'libusb-1.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibusb-1.0, 0x0001): tried: 'liblibusb-1.0' (no such file), '/usr/local/lib/liblibusb-1.0' (no such file), '/usr/lib/liblibusb-1.0' (no such file), '/Users/zsh/Downloads/Client/liblibusb-1.0' (no such file)
   at LibUsbDotNet.NativeMethods.Init(IntPtr& ctx)
   at LibUsbDotNet.LibUsb.UsbContext..ctor()
   at SysDVR.Client.Program.OpenUsbSource(LogLevel usbLogLeve, Boolean forceLibUsb, String preferredSerial)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
```

may be this is clue of some configuration

**Comment by exelix11** [comment]
Basically it can't load any library installed through brew, no clue why this happens, can you post the names of the libusb files you have int /opt/homebrew ?

On the osx runtimes folder i see a file named `libusb-1.0.0.dylib` for in your case it's looking for `libusb-1.0`.

Also when it's ready try this build https://github.com/exelix11/SysDVR/actions/runs/2650144648

**Comment by exelix11** [comment]
Yeah that's what i'm doing, i added custom overrides just for MacOS trying to guess the right path: https://github.com/exelix11/SysDVR/commit/43f9a5c2357cfcb0ea8eccc15597fc2f530c4b98#diff-2ca465883857100b1e083046e0a0e05dfa016daf2b95a1e0401265a7ae55c70bR64-R67

That [build is ready](https://github.com/exelix11/SysDVR/actions/runs/2650144648), let me know if it works

**Comment by AlanLi7991** [comment]
Result from https://github.com/exelix11/SysDVR/actions/runs/2651368804

```
zsh@zshs-M1 Client % dotnet SysDVR-Client.dll usb
SysDVR-Client - SysDVR 5.3 by exelix
https://github.com/exelix11/SysDVR 

Initializing video player with h264 codec.
There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --libdir <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --libdir $(brew --prefix)/lib/

Full error message:
System.DllNotFoundException: Unable to load shared library 'libusb-1.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibusb-1.0, 0x0001): tried: 'liblibusb-1.0' (no such file), '/usr/local/lib/liblibusb-1.0' (no such file), '/usr/lib/liblibusb-1.0' (no such file), '/Users/zsh/Downloads/Client/liblibusb-1.0' (no such file)
   at LibUsbDotNet.NativeMethods.Init(IntPtr& ctx)
   at LibUsbDotNet.LibUsb.UsbContext..ctor()
   at SysDVR.Client.Program.OpenUsbSource(LogLevel usbLogLeve, Boolean forceLibUsb, String preferredSerial)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
zsh@zshs-M1 Client % 
```

**Comment by exelix11** [comment]
Could you to link the libs to /usr/local/lib/ ? that is probably the simple solution we have overlooked till now

**Comment by AlanLi7991** [comment]
yes, actually I tried it, it works ..... may be you could mention this in Readme.... seems no solution right now

**Comment by exelix11** [comment]
Could you try deleting the symlink in /usr/local/lib/  and creating it in the same folder as the dll file ? Cause if that works I may be able to automatically create the symlinks during the first start.

**Comment by AlanLi7991** [comment]
sure, I am thinking it works

```
zsh@zshs-M1 Client % ln -s /opt/homebrew/lib/libavcodec.dylib .
zsh@zshs-M1 Client % ln -s /opt/homebrew/lib/libavutil.dylib . 
zsh@zshs-M1 Client % ln -s /opt/homebrew/lib/libSDL2.dylib .  
zsh@zshs-M1 Client % ln -s /opt/homebrew/lib/libusb-1.0.dylib .
zsh@zshs-M1 Client % dotnet SysDVR-Client.dll usb              
SysDVR-Client - SysDVR 5.3 by exelix
https://github.com/exelix11/SysDVR 

Initializing video player with h264 codec.
ERROR: SysDVR usb device not found.
Make sure that SysDVR is running in usb mode on your console and that you installed the correct driver.
```

**Comment by exelix11** [comment]
Can you try this build whenever it's ready ? https://github.com/exelix11/SysDVR/actions/runs/2663775832 Just extract and run, it will create the needed symlink (only libusb) on its own.

**Comment by AlanLi7991** [comment]
bravo it works perfect !!
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/14807415/179008363-52dde22b-dde0-40b7-831b-c619980e7e38.png">

**Comment by exelix11** [comment]
👍 Will make it in the next release hopefully soon enough.
Thank you for all the testing.

**Comment by AlanLi7991** [comment]
Thanks for your effort of this amazing work
