### ISSUE TITLE
[Help] mac m1 error T_T

### ISSUE THREAD

**Issue by k777007** [exelix11/SysDVR#195]
[To submit a request, fill in all parts of the template and then remove all text in brackets [ ]]

 
**Where is the traffic jam?**
Read all and proceed.net6, ffmpeg, sdl2 After installation is completed
From the terminal in the sysdvr folder, 
The following error occurs when executing the dotnet sysdvr-client.dll usb command: What should I do? I've been trying all week, but it doesn't work out.

**What is the error message?**

 test@testui-MacBookAir SysDVR-Client % dotnet sysdvr-client.dll usb
SysDVR-Client - 5.3 by exelix
https://github.com/exelix11/SysDVR 

System.DllNotFoundException: Unable to load shared library 'avcodec.58.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libavcodec.58.dylib, 0x0001): Library not loaded: /opt/homebrew/Cellar/ffmpeg/5.0.1/lib/libswresample.4.dylib
  Referenced from: /Users/test/Downloads/SysDVR-Client/libavcodec.58.dylib
  Reason: tried: '/opt/homebrew/Cellar/ffmpeg/5.0.1/lib/libswresample.4.dylib' (no such file), '/usr/local/lib/libswresample.4.dylib' (no such file), '/usr/lib/libswresample.4.dylib' (no such file)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at FFmpeg.AutoGen.Native.NativeLibraryLoader.MapMac(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at FFmpeg.AutoGen.ffmpeg.avcodec_find_decoder(AVCodecID id)
   at SysDVR.Client.Player.Player.InitDecoder(Boolean hwAcc)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)

**Setup information**
 - PC OS: [mac m1]
 - Console firmware [e.g. 10.0.0]
 - Custom firmware name and version  Atmo
 - SysDVR version 5.3

**Additional context**

**Comment by exelix11** [comment]
That's been fixed in master but not released yet cause i kept on delaying, you can download a build from github actions which should work.

See also the old closed issues about the m1

**Comment by exelix11** [comment]
I just released [version 5.3.1](https://github.com/exelix11/SysDVR/releases/latest) which should fix this issue, try it and let me know if it works

**Comment by k777007** [comment]
헐..된다. 잘 되요. 빠른 버전 업 매우 감사합니다! 늘 좋은 하루 되시길 바라겠습니다.

**Comment by k777007** [comment]
It works well. It works well in the new version without setting it up. It's just a bug or a home button, adjust the sound or brightness, and go back to the game, and there's no sound in the mac. I'm doing it again by restarting the program. Is this a bug? Is there nothing we can do? Please understand the wrong grammar because it's a translator

**Comment by exelix11** [comment]
Idk maybe it's a mac specific problem or it was just a fluke, seems to work fine on my end.

**Comment by k777007** [comment]
It runs very well, but there is no sound when connecting from tcp (WiFi), is it normal? Sound comes out when connecting to USB

**Comment by exelix11** [comment]
Sometimes it can happen, just try again. If you always get this issue check if you see any error in the terminal window and post it here.

**Comment by k777007** [comment]
When connecting to Wi-Fi, the game is running well, but there is still no sound. (I initialized the Mac today and only installed sysdvr first.) I don't know. I attach the terminal message when I run it. It's running well and there's no soundT_
![9E1CD92C-E19B-40D7-8842-55479D0EA07D](https://user-images.githubusercontent.com/110778654/186419249-eef80b21-0cf3-43a6-a11c-93dafd9aea72.jpeg)
T
