### ISSUE TITLE
I hava a  error  and i don't know how to solve  help me please

### ISSUE THREAD

**Issue by toto55548** [exelix11/SysDVR#196]
Initializing video player with h264 codec.
System.Exception: Assertion failed: -1 WASAPI can't initialize audio client:
   at SysDVR.Client.Player.Exten.Assert(Int32 code, Func`1 MessageFun)
   at SysDVR.Client.Player.Player.InitSDLAudio(AudioStreamTarget target)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)

**Comment by exelix11** [comment]
It seems to be a problem with your sound card, sysdvr can't initialize the audio output.
You can skip audio with the --no-audio command line flag or by selecting to just stream video from the GUI.
