### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lib13520** [exelix11/SysDVR#203]
i got a bug when using both audio and video

but when i use only video in the settings it works 

**Describe the bug**
LibUsbDotNet.LibUsb.UsbException: Operation not supported or unimplemented on this platform
   at LibUsbDotNet.LibUsb.ErrorExtensions.ThrowOnError(Error error)
   at LibUsbDotNet.LibUsb.UsbDevice.ClaimInterface(Int32 interfaceID)
   at SysDVR.Client.Sources.UsbContext.GetForInterface(StreamKind iface)
   at SysDVR.Client.Sources.UsbStreamingSourceBase..ctor(StreamKind kind, UsbContext context)
   at SysDVR.Client.Sources.UsbStreamingSourceWinUsb..ctor(StreamKind kind, UsbContext context)
   at SysDVR.Client.Sources.UsbContext.MakeStreamingSource(StreamKind stream)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)

**Setup information**
 - PC Os: [Fox Os (custom windows 10)
 - Console firmware [14.1.2]
 - Custom firmware name and version [Atmosphere 1.3.2]
 - SysDVR version (5.3)

**Comment by exelix11** [comment]
Reinstall the usb driver then unplug the console and try again

**Comment by lib13520** [comment]
ty works
