### ISSUE TITLE
[Bug] frame_size error when USB streaming to file

### ISSUE THREAD

**Issue by nbubash** [exelix11/SysDVR#228]
**Describe the bug**
USB stream to file save produces error:

  Starting stream, press return to stop.
  [mp2 @ 000001eeb8e5a0c0] frame_size (1152) was not respected for a non-last frame
  Terminating ReceiveFromDeviceThread for Both due to System.Exception: Assertion failed: -22 Unknown error
     at SysDVR.Client.Player.Exten.Assert(Int32 code, Func`1 MessageFun)
     at SysDVR.Client.FileOutput.Mp4AudioTarget.SendFrame(AVFrame* frame)
     at SysDVR.Client.FileOutput.Mp4AudioTarget.SendData(Byte[] data, Int32 size, UInt64 ts)
     at SysDVR.Client.FileOutput.Mp4AudioTarget.SendData(PoolBuffer block, UInt64 ts)
     at SysDVR.Client.MultiStreamThread.DataReceived(PacketHeader& header, PoolBuffer body)
     at SysDVR.Client.StreamThread.DeviceThreadMain(CancellationToken token)

**To Reproduce**
Trying to stream video/audio through USB to a file. Stream to video player and rtsp work fine. I am using the dvr patch.

**Expected behavior**
Save to file.

**Setup information**
 - PC Os: Windows 10 x64
 - Console firmware: 14.1.1
 - Custom firmware name and version: Atmosphere 1.3.2
 - SysDVR version: 5.5.5

**Additional context**
I have tried different computers and cables.

**Comment by exelix11** [comment]
I believe this [build](https://github.com/exelix11/SysDVR/actions/runs/4860252996) should fix the issue, if you confirm i'll go ahead and update the current release

**Comment by nbubash** [comment]
I hadn't tried any previous versions, 5.5.5 is the only one I've used but it does work now and the audio seems to be synced correctly.

**Comment by exelix11** [comment]
I updated the current release with a fix for this, anyone else who is affected just needs to download the client again
