### ISSUE TITLE
[Bug] homebrew doesn't have old version of ffmpeg anymore

### ISSUE THREAD

**Issue by mio-19** [exelix11/SysDVR#243]
```

SysDVR-Client - SysDVR 5.5.6 by exelix
https://github.com/exelix11/SysDVR

There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --libdir <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --libdir $(brew --prefix)/lib/
If you're using an arm based mac make sure you're using native arm dotnet and not the intel one.

Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /opt/homebrew/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
```

The latest ffmpeg comes with 60

**Comment by exelix11** [comment]
You should be able to install an old version using brew install ffmpeg@5 since they provide an older version: https://formulae.brew.sh/formula/ffmpeg@5

I know this is not optimal but i need a common version of native libraries for cross platform support, i'm working on a simpler solution by shipping all libraries in a single zip for each platform but in the meantime that's the best we have.
