### ISSUE TITLE
[Help] command "dotnet SysDVR-Client.dll" failed

### ISSUE THREAD

**Issue by meeteliza** [exelix11/SysDVR#249]
Hi, thank you for creating such a helpful tool!

---------my error description---------
I finished installing all dependencies (dotnet, ffmpeg@5, SDL2, libusb)
and checked "dotnet SysDVR-Client.dll --help" (see p1) which worked successfully
<img width="513" alt="截屏2023-09-14 20 14 19" src="https://github.com/exelix11/SysDVR/assets/66713767/6b135ce4-63e2-4242-958f-ac32d255342e">
but I have trouble running the "dotnet SysDVR-Client.dll" command.
this is the full error message:
![Uploading 截屏2023-09-14 20.07.55.png…]()

Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /usr/local/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)

it suggests me to look at my “dynamic loader environment variable”
but unfortunately I don't know what that means
so I really appreciate if you can help explain

-------my  Setup information-----------
 - PC OS: Mac OS ventura 
 - Custom firmware name and version: Atmosphere 16.03
 - SysDVR version: 5.5.6

Thanks again

**Comment by meeteliza** [comment]
good news: I figured it out myself lol!
here I find a detailed instruction on how to move some files into the right direction
https://gist.github.com/c01dc0ffee/8acbd11bbd4b5c18ba4c5de288deb423
Im so happy when my switch screen pops up on my Mac
thanks again for your wonderful tool!
