### ISSUE TITLE
[Linux] [via USB] Warning: Couldn't write data to device (Video/Audio thread)

### ISSUE THREAD

**Issue by reinzanini** [exelix11/SysDVR#42]
Arch Linux. Have both `libusb` and the latest `dotnet-runtime`. I am using the USB-only version of SysDVR. After running `$ sudo dotnet SysDVR-Client.dll` (not `$ sudo dotnet SysDVR-Client.dll rtsp` because that way I get some "Unhandled expection" error) I get this:
```
SysDVR-Client - 3.0 by exelix
https://github.com/exelix11/SysDVR 

Starting stream, press return to stop
If the stream lags try pausing and unpausing the player.
Now streaming via RTSP on port 6666
Connect with your player to rtsp://127.0.0.1:6666/
```
Then I simply `mpv rtsp://127.0.0.1:6666/` in another window and SysDVR throws this:
```
Connection from 127.0.0.1:40464
RTSP message received Rtsp.Messages.RtspRequestOptions
RTSP message received Rtsp.Messages.RtspRequestDescribe
Request for rtsp://127.0.0.1:6666/
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestPlay
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)
Warning: Couldn't write data to device (Video thread)
Warning: Couldn't write data to device (Audio thread)

```
And basically goes forever with this "couldn't write data" warning.
mpv doesn't start, after I suspend the SysDVR command it gives me this:
```
$ mpv rtsp://127.0.0.1:6666/
[ffmpeg/video] h264: missing picture in access unit with size 28
[ffmpeg/video] h264: no frame!
[ffmpeg/demuxer] rtsp: Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' and 'probesize' options
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (pcm_s16be 2ch 48000Hz)
File tags:
 Title: Vstream test
Cannot load libcuda.so.1
[ffmpeg/video] h264: no frame!
Error while decoding frame (hardware decoding)!
```

**Comment by exelix11** [comment]
Unfortunately i can't seem to reproduce this issue, just tried on my ubuntu VM and it works fine.
Guess it could have to do with your libusb version, you can try running sysdvr-client with the `--usb-warn` or `--usb-debug` args and check if the output helps you (the latter includes the first).
Maybe searching in the issue tracker of [LibUsbDotNet](https://github.com/LibUsbDotNet/LibUsbDotNet) you can find something helpful.

About the error you get with the rtsp arg it's likely the race condition described in [issue 33](https://github.com/exelix11/SysDVR/issues/33#issuecomment-592484119) there's also a build that fixes it. Interestingly almost nobody seems to have it on windows but i had it regardless of the args on ubuntu.
In case the provided build doesn't fix that issue please post the full exception message.

**Comment by reinzanini** [comment]
Tried with the debug version, sometimes it gives the error in this thread other times this:
```
$ sudo dotnet SysDVR-Client.dll rtsp --usb-debug
SysDVR-Client - 3.0 by exelix
https://github.com/exelix11/SysDVR 

Starting stream, press return to stop
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.039774] [000089bc] libusb: debug [libusb_get_device_list] 
[ 0.045155] [000089bc] libusb: debug [libusb_get_device_descriptor] 
[ 0.047717] [000089bc] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.047737] [000089bc] libusb: debug [parse_endpoint] skipping descriptor 30
[ 0.053885] [000089bc] libusb: debug [libusb_get_device_descriptor] 
[ 0.053908] [000089bc] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.053960] [000089bc] libusb: debug [libusb_get_device_descriptor] 
[ 0.053974] [000089bc] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.053989] [000089bc] libusb: debug [parse_configuration] skipping descriptor 0xb
[ 0.054002] [000089bc] libusb: debug [parse_endpoint] skipping descriptor 25
[ 0.054049] [000089bc] libusb: debug [libusb_get_device_descriptor] 
[ 0.054061] [000089bc] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.054088] [000089bc] libusb: debug [libusb_get_device_descriptor] 
[ 0.054101] [000089bc] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.054953] [000089bc] libusb: debug [libusb_open] open 1.15
[ 0.167014] [000089bc] libusb: debug [usbi_add_pollfd] add fd 46 events 4
[ 0.169438] [000089bc] libusb: debug [libusb_get_device_descriptor] 
[ 0.170978] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca14e0d0
[ 0.171013] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca14e0d0
[ 0.171034] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.171112] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.171140] [000089bc] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.171180] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.171491] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.171527] [000089bc] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=4
[ 0.171547] [000089bc] libusb: debug [handle_control_completion] handling completion status 0
[ 0.171577] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.171609] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca14e0d0 has callback 0x7f669ba12590
[ 0.171639] [000089bc] libusb: debug [sync_transfer_cb] actual_length=4
[ 0.171673] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca14e0d0
[ 0.171695] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca14e1f0
[ 0.171721] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca14e1f0
[ 0.171740] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.171791] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.171818] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.172088] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.172121] [000089bc] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=14
[ 0.172141] [000089bc] libusb: debug [handle_control_completion] handling completion status 0
[ 0.172284] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.172309] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca14e1f0 has callback 0x7f669ba12590
[ 0.172445] [000089bc] libusb: debug [sync_transfer_cb] actual_length=14
[ 0.172471] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca14e1f0
[ 0.173328] [000089bc] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.173389] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca14e820
[ 0.173527] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca14e820
[ 0.173546] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.173703] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.173728] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.173980] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.173999] [000089bc] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=4
[ 0.174009] [000089bc] libusb: debug [handle_control_completion] handling completion status 0
[ 0.174020] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.174096] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca14e820 has callback 0x7f669ba12590
[ 0.174106] [000089bc] libusb: debug [sync_transfer_cb] actual_length=4
[ 0.174120] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca14e820
[ 0.174187] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca131d40
[ 0.174196] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca131d40
[ 0.174205] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.174278] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.174290] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.174522] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.174537] [000089bc] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=50
[ 0.174546] [000089bc] libusb: debug [handle_control_completion] handling completion status 0
[ 0.174556] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.174567] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca131d40 has callback 0x7f669ba12590
[ 0.174630] [000089bc] libusb: debug [sync_transfer_cb] actual_length=50
[ 0.174642] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca131d40
[ 0.174659] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca131d40
[ 0.174723] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca131d40
[ 0.174786] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.174908] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.174921] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.175148] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.175163] [000089bc] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=4
[ 0.175226] [000089bc] libusb: debug [handle_control_completion] handling completion status 0
[ 0.175290] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.175357] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca131d40 has callback 0x7f669ba12590
[ 0.175420] [000089bc] libusb: debug [sync_transfer_cb] actual_length=4
[ 0.175485] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca131d40
[ 0.175549] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca131d40
[ 0.175614] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca131d40
[ 0.175678] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.175801] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.175813] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.176041] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.176057] [000089bc] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=70
[ 0.176122] [000089bc] libusb: debug [handle_control_completion] handling completion status 0
[ 0.176205] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.176270] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca131d40 has callback 0x7f669ba12590
[ 0.176334] [000089bc] libusb: debug [sync_transfer_cb] actual_length=70
[ 0.176399] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca131d40
[ 0.177747] [000089bc] libusb: debug [libusb_claim_interface] interface 0
[ 0.182028] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca14e600
[ 0.182053] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca14e600
[ 0.182075] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 10ms (first in line)
[ 0.182095] [000089bc] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.182124] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.182138] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.192161] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.192244] [000089bc] libusb: debug [handle_events] timerfd triggered
[ 0.192254] [000089bc] libusb: debug [libusb_cancel_transfer] transfer 0x5648ca14e600
[ 0.192397] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.192415] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.192426] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.192438] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.192460] [000089bc] libusb: debug [reap_for_handle] urb type=3 status=-2 transferred=0
[ 0.192473] [000089bc] libusb: debug [handle_bulk_completion] handling completion status -2 of bulk urb 1/1
[ 0.192487] [000089bc] libusb: debug [handle_bulk_completion] abnormal reap: urb status -2
[ 0.192502] [000089bc] libusb: debug [handle_bulk_completion] abnormal reap: last URB handled, reporting
[ 0.192513] [000089bc] libusb: debug [usbi_handle_transfer_cancellation] detected timeout cancellation
[ 0.192525] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.192540] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca14e600 has callback 0x7f669ba12590
[ 0.192558] [000089bc] libusb: debug [sync_transfer_cb] actual_length=0
[ 0.192574] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca14e600
[ 0.195550] [000089bc] libusb: debug [libusb_alloc_transfer] transfer 0x5648ca131730
[ 0.195568] [000089bc] libusb: debug [libusb_submit_transfer] transfer 0x5648ca131730
[ 0.195595] [000089bc] libusb: debug [add_to_flying_list] arm timerfd for timeout in 10ms (first in line)
[ 0.195609] [000089bc] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
[ 0.195639] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.195653] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.205676] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.205711] [000089bc] libusb: debug [handle_events] timerfd triggered
[ 0.205732] [000089bc] libusb: debug [libusb_cancel_transfer] transfer 0x5648ca131730
[ 0.205869] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.205897] [000089bc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.205918] [000089bc] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.205943] [000089bc] libusb: debug [handle_events] poll() returned 1
[ 0.205967] [000089bc] libusb: debug [reap_for_handle] urb type=3 status=-2 transferred=0
[ 0.205988] [000089bc] libusb: debug [handle_bulk_completion] handling completion status -2 of bulk urb 1/1
[ 0.206007] [000089bc] libusb: debug [handle_bulk_completion] abnormal reap: urb status -2
[ 0.206027] [000089bc] libusb: debug [handle_bulk_completion] abnormal reap: last URB handled, reporting
[ 0.206047] [000089bc] libusb: debug [usbi_handle_transfer_cancellation] detected timeout cancellation
[ 0.206067] [000089bc] libusb: debug [disarm_timerfd] 
[ 0.206089] [000089bc] libusb: debug [usbi_handle_transfer_completion] transfer 0x5648ca131730 has callback 0x7f669ba12590
[ 0.206109] [000089bc] libusb: debug [sync_transfer_cb] actual_length=0
[ 0.206132] [000089bc] libusb: debug [libusb_free_transfer] transfer 0x5648ca131730
If the stream lags try pausing and unpausing the player.
[ 0.216215] [000089c7] libusb: debug [libusb_alloc_transfer] transfer 0x7f65e40018c0
[ 0.216242] [000089c7] libusb: debug [libusb_submit_transfer] transfer 0x7f65e40018c0
[ 0.216264] [000089c7] libusb: debug [add_to_flying_list] arm timerfd for timeout in 10000ms (first in line)
[ 0.216279] [000089c7] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 4
[ 0.216307] [000089c7] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.216319] [000089c7] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
Unhandled exception. [ 0.239705] [000089c6] libusb: debug [libusb_alloc_transfer] transfer 0x7f65e00065d0
[ 0.239827] [000089c6] libusb: debug [libusb_submit_transfer] transfer 0x7f65e00065d0
[ 0.239932] [000089c6] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 4
[ 0.240055] [000089c6] libusb: debug [libusb_handle_events_timeout_completed] another thread is doing event handling
System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at SysDVRClient.RTSP.RtspServer.StartListenerThread()
   at SysDVRClient.RTSP.SysDvrRTSPServer.Begin()
   at SysDVRClient.Program.StartManagedStreaming(IMutliStreamManager Streams, String[] args)
   at SysDVRClient.Program.StartUsbStreaming(IMutliStreamManager Streams, String[] args)
   at SysDVRClient.Program.Main(String[] args)
[2]    35259 abort      sudo dotnet SysDVR-Client.dll rtsp --usb-debug
```

I doubt it's the wire since it works well.

**Comment by exelix11** [comment]
It seems it can't bind to port 6666 for some reason, maybe you still have another instance running in background ?

**Comment by reinzanini** [comment]
Yeah, that did it. Thanks and sorry for the delayed answer.
