### ISSUE TITLE
[Help] Unhandled exception. System.Net.Sockets.SocketException (10013)

### ISSUE THREAD

**Issue by modman2k20** [exelix11/SysDVR#71]
**Where do you get stuck ?**
When I launch Sysdvr GUI and launch over USB I get the error below. I have disabled my firewall and antivirus but still have the issue. I've also tried to reinstall the drivers numerous times and restart the computer but i still get this issue.

**What's the error message you get ?**
Starting stream, press return to stop
If the stream lags try pausing and unpausing the player.
Unhandled exception. System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at SysDVRClient.RTSP.RtspServer.StartListenerThread()
   at SysDVRClient.RTSP.SysDvrRTSPManager.Begin()
   at SysDVRClient.Program.StartStreaming(BaseStreamManager Streams)
   at SysDVRClient.Program.Main(String[] args)

**Setup information**
 - PC OS: Windows 10 x64
 - Console firmware: 10.0.4
 - Custom firmware name and version: Atmosphere 0.13.0
 - SysDVR version: 4.0.1

**Comment by exelix11** [comment]
Sounds like port 6666 on your pc is being used by something else, bluestacks is a known offender. You can check using `netstat -bn` in an admin command prompt, kill the process using that port and try again.
You can also change Sysdvr port but only from the commandl line interface, check `sysdvr-clent --help`

**Comment by Icing-weaponry** [comment]
I got the same error on my end
I checked with netstat -bn but nothing is using port 6666

**Comment by exelix11** [comment]
Have you tried changing port with the command line option?
Also thought maybe netstat is not very intuitive, try using [tcpview](https://docs.microsoft.com/it-it/sysinternals/downloads/tcpview) to figure out if the port is in use. If it's not then sysdvr should work.

**Comment by doanja** [comment]
How do you change the sysdvr port? I am on Windows x64 btw.

**Comment by exelix11** [comment]
With the `--rtsp-port` option from the command line, it's not possible from the GUI.

**Comment by doanja** [comment]
Sorry I meant to ask how do you run the commands? Am I suppose to run the commands in the directory of the SysDvr in cmd?

**Comment by exelix11** [comment]
Yes, you should follow the SysDVR-client parts of the guide instead of the GUI ones.
If you're not used to running commands with cmd you can export the configuration from the GUI as bat and edit it in notepad to change the port, you just need to add `--rtsp-port 9999` at the end of the first line

**Comment by exelix11** [comment]
Closing due to inactivity.
