### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by javok3000** [exelix11/SysDVR#96]
**Where do you get stuck ?**
[Which step of the guide ? Did you read the Troubleshooting section at the end ?]

**What's the error message you get ?**
cmd text
Initializing video player with h264 codec.
Unhandled exception. System.Exception: Invalid channel count
   at SysDVR.Client.Player.Player.InitSDLAudio(AudioStreamTarget target)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName)
   at SysDVR.Client.Program.Main(String[] args)

**Setup information**
 - PC OS: Windows 10 x64
 - Console firmware 10.2.0
 - Custom firmware name and version Atmosphere 0.15.0
 - SysDVR version 5.0

Sorry to bother you again, it just stop working after some hours

**Comment by exelix11** [comment]
Happens if you have an audio device with more than two channels, either switch to stereo mode or use the last build provided in https://github.com/exelix11/SysDVR/issues/94 , in case that doesn't work reply there as this specific error is already being tracked in that issue.
